server:
  port: 8081

spring:
  profiles:
    active: ${RUN_MODE:local}

tf:
  springboot:
    kafka:
      bootstrapServer: "localhost:9093"
      topic: "topic-test"
      groupId: "group-test"
      topicPattern: "topic-.*"
      producer:
        enabled: true