server:
  port: 8082

spring:
  profiles:
    active: ${RUN_MODE:local}

tf:
  springboot:
    kafka:
      bootstrapServer: "localhost:9093"
      topic: "topic-test"
      groupId: "group-test"
      consumer:
        enabled: true